//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl", ConfigurationName="ServiceReference.IWCFRequestHandler")]
    public interface IWCFRequestHandler {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddEvent", ReplyAction="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddEventResponse")]
        void addEvent(org.owasp.appsensor.Event Event);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddEvent", ReplyAction="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddEventResponse")]
        System.Threading.Tasks.Task addEventAsync(org.owasp.appsensor.Event Event);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddAttack", ReplyAction="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddAttackResponse")]
        void addAttack(org.owasp.appsensor.Attack attack);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddAttack", ReplyAction="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/a" +
            "ddAttackResponse")]
        System.Threading.Tasks.Task addAttackAsync(org.owasp.appsensor.Attack attack);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/g" +
            "etResponses", ReplyAction="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/g" +
            "etResponsesResponse")]
        org.owasp.appsensor.Response[] getResponses(string earliest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/g" +
            "etResponses", ReplyAction="https://www.owasp.org/index.php/OWASP_AppSensor_Project/wsdl/IWCFRequestHandler/g" +
            "etResponsesResponse")]
        System.Threading.Tasks.Task<org.owasp.appsensor.Response[]> getResponsesAsync(string earliest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFRequestHandlerChannel : UnitTests.ServiceReference.IWCFRequestHandler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFRequestHandlerClient : System.ServiceModel.ClientBase<UnitTests.ServiceReference.IWCFRequestHandler>, UnitTests.ServiceReference.IWCFRequestHandler {
        
        public WCFRequestHandlerClient() {
        }
        
        public WCFRequestHandlerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFRequestHandlerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFRequestHandlerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFRequestHandlerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addEvent(org.owasp.appsensor.Event Event) {
            base.Channel.addEvent(Event);
        }
        
        public System.Threading.Tasks.Task addEventAsync(org.owasp.appsensor.Event Event) {
            return base.Channel.addEventAsync(Event);
        }
        
        public void addAttack(org.owasp.appsensor.Attack attack) {
            base.Channel.addAttack(attack);
        }
        
        public System.Threading.Tasks.Task addAttackAsync(org.owasp.appsensor.Attack attack) {
            return base.Channel.addAttackAsync(attack);
        }
        
        public org.owasp.appsensor.Response[] getResponses(string earliest) {
            return base.Channel.getResponses(earliest);
        }
        
        public System.Threading.Tasks.Task<org.owasp.appsensor.Response[]> getResponsesAsync(string earliest) {
            return base.Channel.getResponsesAsync(earliest);
        }
    }
}
